#!/usr/bin/env bash
#  Tests for 'http_api' initialization.
set -euo pipefail
IFS=$'\n\t'


#  -test Output directory exists
assertTrue "Output directory is not found" "-d output"


#  -test Workspace directory exists
assertTrue "Workspace directory is not found" "-d ws"


#  -test Config file exists
assertTrue "Config JSON is not found" "-f ws/config.json"
