#!/usr/bin/env bash
#  Tests for 'http_api' internal functions.
set -euo pipefail
IFS=$'\n\t'


#  -test Script clean-up
echo '{}' > ws/cleanable_config.json.tmp

_finally_http_api

assertFalse "Workspace file is currently exists" "-f ws/cleanable_config.json.tmp"
