#! /usr/bin/env bash
#  Tests for 'http_api' public functions.


#  -beforeTest
OUTPUT="output/public-output.$$"
echo '{"id":"5s43u-323we"}' > "$OUTPUT.output"


#  -test Update JSON config file
update "ws/config.json" ". + { \"update\": \"updated\" }"
_update=$( cat "ws/config.json" | jq ".update" )
assertEquals "'update' not found" "\"updated\"" "$_update"

update "ws/config.json" "del(.update)"
_update=$( cat "ws/config.json" | jq ".update" )
assertEquals "'update' was found" "null" "$_update"


#  -test Put key-value config
put '.id'
_id=$( cat "ws/config.json" | jq ".id" )
assertEquals "'id' not found" "\"5s43u-323we\"" "$_id"

put 'jqId' '.id'
_jqId=$( cat "ws/config.json" | jq ".jqId" )
assertEquals "'jqId' not found" "\"5s43u-323we\"" "$_jqId"

put 'rawId' '"4jj43-34mdwe"'
_rawId=$( cat "ws/config.json" | jq ".rawId" )
assertEquals "'rawId' not found" "\"4jj43-34mdwe\"" "$_rawId"

put 'idx' 5
_idx=$( cat "ws/config.json" | jq ".idx" )
assertEquals "'idx' not found" "5" "$_idx"

put 'flag' true
_flag=$( cat "ws/config.json" | jq ".flag" )
assertEquals "'flag' not found" "true" "$_flag"

put 'null' null
_null=$( cat "ws/config.json" | jq ".null" )
assertEquals "'null' not found" "null" "$_null"

put 'object' '{}'
_object=$( cat "ws/config.json" | jq ".object" )
assertEquals "'object' not found" "{}" "$_object"


#  -test Get key-value config
_id=$( get id )
assertEquals "'id' not found" "5s43u-323we" "$_id"

_jqId=$( get jqId )
assertEquals "'jqId' not found" "5s43u-323we" "$_jqId"

_rawId=$( get rawId )
assertEquals "'rawId' not found" "4jj43-34mdwe" "$_rawId"

_idx=$( get idx )
assertEquals "'idx' not found" "5" "$_idx"

_flag=$( get flag )
assertEquals "'flag' not found" "true" "$_flag"

_null=$( get null )
assertEquals "'null' not found" "null" "$_null"

_object=$( get object )
assertEquals "'object' not found" "{}" "$_object"

_unknown=$( get unknown )
assertEquals "'unknown' was found" "null" "$_unknown"

fail "Get temporal - Not implemented yet"


#  -test Remove key-value config
remove '.id'
_id=$( get id )
assertEquals "'id' was found" "null" "$_id"

remove jqId
_jqId=$( get jqId )
assertEquals "'jqId' was found" "null" "$_jqId"

remove rawId
_rawId=$( get rawId )
assertEquals "'rawId' was found" "null" "$_rawId"

remove idx
_idx=$( get idx )
assertEquals "'idx' was found" "null" "$_idx"

remove flag
_flag=$( get flag )
assertEquals "'flag' was found" "null" "$_flag"

remove null
_null=$( get null )
assertEquals "'null' was found" "null" "$_null"

remove object
_object=$( get object )
assertEquals "'object' was found" "null" "$_object"

remove unknown
_unknown=$( get unknown )
assertEquals "'unknown' was found" "null" "$_unknown"
