#! /usr/bin/env bash
#  Global before tests.
#  This is imported by 'test_runner'.
#  -author Giovanni Farfán B.


#  Set-up mock services.
cd mock
./setup_mock
cd ..


#  Mark as skip 'http_api' main code.
#  shellcheck disable=SC2034
SKIP_HTTP_API=true

#  Import 'http_api'
#  shellcheck disable=SC1091
. ../http_api
