#! /usr/bin/env bash
#  Global after tests.
#  This is imported by 'test_runner'.
#  -author Giovanni Farfan B.


#  Clean-up generated directories
#+ because 'shttp'
rm -rf output
#rm -rf hist
rm -rf ws


#  Clean-up mock services.
(
    cd mock || exit
    ./clean_mock
)
