#! /usr/bin/env bash
#  Global after tests.
#  This is imported by 'test_runner'.
#  -author Giovanni Farfán B.


#  Clean-up generated directories
#+ because 'http_api'
rm -rf output
rm -rf hist
rm -rf ws


#  Clean-up mock services.
(
    cd mock || exit
    ./clean_mock
)
