#! /usr/bin/env bash
#  Global before tests.
#  This is imported by 'test_runner'.
#  -author Giovanni Farfan B.


#  Set-up mock services.
(
    cd mock || exit
    ./setup_mock
)

#  Mark as skip 'shttp' main code.
#  shellcheck disable=SC2034
SKIP_HTTP_API=true

#  Import 'shttp'
#  shellcheck disable=SC1091
. ../shttp
