#! /usr/bin/env bash
#  Enables Slack notifications.
#  -author Giovanni Farfan B.

#  Slack notifications flag.
_slack_enabled=0

# Set to enable Slack
#+ notifications flag.
#  No test required.
_set_slack_enabled() {
    _slack_enabled=1
}
#  Documentation for help content
_help_content \
    "   --slack:                          Enables Slack notifications"
#  New option is added
_register_opt --slack _set_slack_enabled REQUEST
if expr "$*" : ".*--slack" > /dev/null; then
    _look_for_params --slack "$@"
fi

#  This will be call inside of
#+ '_notify_execution' execution
#+ (as part of lifecycle execution).
#
#  -param $1 Notification level
#  -param $2 Notification message
proceed_notif() {
    if [ $_slack_enabled != 1 ]; then
        return 0
    fi
    local _level=${1:-}
    local _message=${2:-}
    local _slack=""
    _slack="https://hooks.slack.com/services/$( get slackSrv )"
    case "$_level" in
        INFO) 
            local _icon=":information_source:"
        ;;
        WARNING)
            local _icon=":warning:"
        ;;
        ERROR)
            local _icon=":rotating_light:"
        ;;
        *)
            local _icon=":grey_exclamation:"
        ;;
    esac
    #  shellcheck disable=SC2154
    curl -X POST -s -H "Content-type: application/json" \
        --data "{
            \"text\":\"$_icon $_message\",
            \"username\":\"${_shttp_basename%.*}\",
            \"icon_emoji\":\":slack:\"
            }" \
        "$_slack"
}
