#! /usr/bin/env bash
#  Mock service cleaner.
#  -author Giovanni Farfán B.
set -euo pipefail
IFS=$'\n\t'


#  Check installation and
#+ stop service.
nginx -v
service nginx stop
service nginx status


#  Clean-up Nginx server
readonly _nginx_available="/etc/nginx/sites-available/"
readonly _nginx_enabled="/etc/nginx/sites-enabled/"

rm -rf "${_nginx_available}shttp"*
rm -rf "${_nginx_enabled}shttp"*
