#! /usr/bin/env bash
#  Mock service cleaner.
#  -author Giovanni Farfán B.
set -euo pipefail
IFS=$'\n\t'

#  Check installation and
#+ stop service.
nginx -v
service nginx stop


#  Clean-up Nginx server
rm -rf /etc/nginx/sites-available/shttp*
rm -rf /etc/nginx/sites-enabled/shttp*
