#! /usr/bin/env bash
#  Mock service cleaner.
#  -author Giovanni Farfán B.
set -euo pipefail
IFS=$'\n\t'


#  Check installation and
#+ stop service.
nginx -v
service nginx stop


#  Remove services files.
readonly _nginx_share="/usr/share/nginx/"
rm -rf "${_nginx_share}shttp_mock"


#  Clean-up Nginx server
readonly _nginx_available="/etc/nginx/sites-available/"
readonly _nginx_enabled="/etc/nginx/sites-enabled/"
readonly _mock_conf="shttp_mock.conf"

rm -f $_nginx_available$_mock_conf
rm -f $_nginx_enabled$_mock_conf


#  Validate set-down
if [ -d ${_nginx_share}shttp_mock ] \
    || [ -f $_nginx_available$_mock_conf ] \
    || [ -f $_nginx_enabled$_mock_conf ]; then
    printf "\r%*s\r%s\n" "$(tput cols)" "[ FAILED ] " "setup_mock: Mock services set-down failed";
    exit 1
else
    printf "\r%*s\r%s\n" "$(tput cols)" "[ OK ] " "setup_mock: Mock services correctly set-down";
fi
