#! /usr/bin/env bash
#  Mock service configurator.
#  -author Giovanni Farfán B.
set -euo pipefail
IFS=$'\n\t'

#  Check installation and
#+ stop service.
nginx -v
service nginx stop


#  Set-up Nginx server
readonly _srv_location="$( pwd )/srv"
readonly _mock_conf="shttp_mock.conf"

# Clean-up last files in available sites
rm -rf /etc/nginx/sites-available/shttp*

#  Copy server configuration
cp $_mock_conf /etc/nginx/sites-available/

#  Put correct service location
sed -i -e "s|{{_shttp_srv_location}}|$_srv_location|g" "/etc/nginx/sites-available/$_mock_conf"

cat "/etc/nginx/sites-available/$_mock_conf"

# Clean-up last files in enabled sites
rm -rf /etc/nginx/sites-enabled/shttp*

#  Enable site by creating a symbolic link
ln -s /etc/nginx/sites-available/$_mock_conf /etc/nginx/sites-enabled/ 

nginx -t
service nginx start
