
language: bash

branches:
  only:
    - master

install:
  - scversion="latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - shellcheck --version
  
script:
  - ./lint
  - ./runtests
