language: bash

services:
  - docker

branches:
  only:
    - master

install:
  - docker pull gfarfanb/shttp:1.0.0
  - docker run -it -d --name shttp-test-env -P -v $TRAVIS_BUILD_DIR:/usr/src/app gfarfanb/shttp:1.0.0

before-script:
  - docker ps -a

script:
  - docker exec shttp-test-env ./lint
  - docker exec -e DEBUG_MODE='$DEBUG_MODE' shttp-test-env ./runtests

after_script:
  - docker rm -f shttp-test-env
