language: bash

services:
  - docker

branches:
  only:
    - master

before_install:
- docker pull gfarfanb/shttp:1.0.0
- docker run -d --name shttp -P -v $HOME/gfarfanb/shTTP:/usr/src/app gfarfanb/shttp:1.0.0 /bin/bash
- docker ps -a

script:
  - docker exec shttp ./lint
  - docker exec shttp ./runtests
