sudo: required

language: bash

branches:
  only:
    - master

addons:
  apt:
    packages:
      - nginx

install:
  - curl --version
  - jq --version
  - shellcheck --version
  - nginx -v

script:
  - ./lint
  - sudo ./runtests
