sudo: required

language: bash

branches:
  only:
    - master

install:
  - curl --version
  - sudo apt-get install jq
  - sudo apt-get install shellcheck
  - sudo apt-get install nginx

script:
  - ./lint
  - sudo ./runtests
