language: bash
sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker pull gfarfanb/shttp:1.0.0
  - docker run -it -d --name shttp-test-env -P -v $TRAVIS_BUILD_DIR:/usr/src/app gfarfanb/shttp:1.0.0

before-script:
  - docker ps -a

script:
  - sudo docker exec shttp-test-env ./lint
  - sudo docker exec shttp-test-env ./runtests
  - sudo docker exec shttp-test-env ./runsamples $SAMPLE_USER $SAMPLE_PASSWORD $SAMPLE_KEY $SAMPLE_SECRET

after_script:
  - docker rm -f shttp-test-env
