#! /usr/bin/env bash
#  Simple HTTP API development environment.
#  -author Giovanni Farfán B.
set -euo pipefail
IFS=$'\n\t'

#  Show the help content.
_shttp_help_content() {
    local _content=(
        ""
        " Usage: ./<file>.sh <command> [--set <key-name> <value>] [--get <key-name>] [--add <key-name> <value>]"
        "                              [--remove <key-name>] [--get-keys] [--list] [--clean] [--host <host>]"
        "                              [--local <port>] [--auth-header] [--auth-qparam] [--open] [--help]"
        ""
        " Options:"
        "   --set <key-name> <value>:  Set a temporal key-value config. This won't saved to 'ws/config.json'"
        "   --get <key-name>:          Display the value for key from 'ws/config.json'"
        "   --add <key-name> <value>:  Add new key-value to 'ws/config.json'"
        "   --remove <key-name>:       Remove the key-value from 'ws/config.json'"
        "   --get-keys:                Display all keys from 'ws/config.json' file"
        "   --list:                    Display the <command> list (all functions defined into main script)"
        "   --clean:                   Clean up all output files 'output/*'"
        "   --host <host>:             Set host value to 'host' in 'ws/config.json'"
        "   --local <port>:            Set variables to local execution:"
        "                                _shttp_protocol: http"
        "                                _shttp_domain: localhost:<port> (default 8080)"
        "   --auth-header:             Set 'HEADER' to 'AUTH_MODE' for headers authorization."
        "   --auth-qparam:             Set 'QPARAM' to 'AUTH_MODE' for query params authorization."
        "   --open:                    Set 'EDITOR_COMMAND' with value defined on 'editorCommand' from 'ws/config.json'"
        "   --help:                    Display this help message"
    )
    echo "${_content[*]}"
}
expr "$*" : ".*--help" > /dev/null \
    && _shttp_help_content \
    && exit 0


#  Script filename.
readonly _shttp_basename=$( basename "$0" )


# ---------- Logging functions

#  Log filename.
readonly _shttp_log_file="/tmp/shTTP_${_shttp_basename%.*}.$( date '+%Y-%m-%d' ).log"

#  Log a message object with the INFO level.
#
#  -param $* Log message
info() { echo "$( date '+%Y-%m-%d %T.%N' ) [INFO]    $*" | tee -a "$_shttp_log_file" >&2 ; }

#  Log a message object with the WARNING level.
#
#  -param $* Log message
warning() { echo "$( date '+%Y-%m-%d %T.%N' ) [WARNING] $*" | tee -a "$_shttp_log_file" >&2 ; }

#  Log a message object with the ERROR level.
#
#  -param $* Log message
error() { echo "$( date '+%Y-%m-%d %T.%N' ) [ERROR]   $*" | tee -a "$_shttp_log_file" >&2 ; }

#  Log a message object with the FATAL level, 
#+ exit execution with 1.
#
#  -param $* Log message
fatal() { echo "$( date '+%Y-%m-%d %T.%N' ) [FATAL]   $*" | tee -a "$_shttp_log_file" >&2 ; exit 1 ; }


# ---------- Initialization

# 'cURL' is required
readonly _curl_version=$( curl --version )
if [ -z "$_curl_version" ]; then
    fatal "'curl' is not installed yet"
fi
#  'jq' (command-line JSON processor) is required
#+ https://github.com/stedolan/jq
readonly _jq_version=$( jq --version )
if [ -z "$_jq_version" ]; then
    fatal "'jq' is not installed yet"
fi
#  Output directory for trace and results files
if ! [ -d output ]; then 
    mkdir output || fatal "Imposible to create 'output' dorectory"
fi
#  Workspace directory for data execution
if ! [ -d ws ]; then 
    mkdir ws || fatal "Imposible to create 'ws' dorectory"
fi
#  Config JSON file
if ! [ -f "ws/config.json" ]; then
    echo '{ "host": null, "hosts": [] }' > "ws/config.json"
fi


# ---------- Util functions

#  Reverse the string input.
#
#  -param $1 String input
_rev() {
    local _input=${1:-''}
    local _rev=""
    for (( i=${#_input}-1; i>=0; i-- )); do 
        _rev="$_rev${_input:$i:1}"
    done
    echo "$_rev"
}


# ---------- Public functions

#  Update a JSON file using 'jq'.
#
#  -param $1 JSON file
#  -param $2 Change by 'jq'
update() {
    local _json=${1:-''}
    local _jq=${2:-''}
    local _temp=""
    _temp="ws/config.$( date '+%s.%N' ).json.tmp"
    jq "$_jq" "$_json" > "$_temp"
    mv "$_temp" "$_json"
}

#  Save key-value config to 'ws/config.json'.
#  This function has three different forms:
#    1. Only 'jq' query: put '.jq'
#    2. Name and 'jq' query: put 'name' '.jq'
#    3. Name and value: put 'name' 'value'
#  If 'jq' query is found, the function will
#+ use JSON result to take the value.
#
#  -param $1 Name of the entry or 'jq' for value
#  -param $2 Value of the entry or 'jq' for value
put() {
    local _name=${1:-''}
    local _val=${2:-''}
    local _jq=""
    if [ -z "$_val" ]; then
        _jq="$_name"
        _name=${_name//[0-9^\[\]]/}
        _name=$( _rev "$_name" )
        _name=$( echo "$_name" | cut -d '.' -f 1 )
        _name=$( _rev "$_name" )
    elif [[ "$_val" = \.* ]]; then
        _jq="$_val"
    fi
    if [ -n "$_jq" ]; then
        _val=$( < "$OUTPUT.output" jq "try $_jq catch null" )
    fi
    update "ws/config.json" ". + { \"$_name\": $_val }"
    info "Saved [$_name] with value [$_val] to workspace config"
}

#  Get key-value config in the following
#+ order: script variables and then from
#+ 'ws/config.json'.
#
#  -param $1 Name of the entry or 'jq'
#+           query (without '.' at the
#+           beginning of the query)
#  -param $1 Default value if required
#+           is not found
get() {
    local _name=${1:-''}
    local _default=${2:-'null'}
    local _val=""
    if [[ "$_name" =~ ^[a-zA-Z]*$ ]]; then
        _val=$( eval "echo \${$_name:-''}" )
    fi
    if [ -z "$_val" ]; then
        _val=$( jq ".$_name | tostring" "ws/config.json" )
        _val=$( echo "$_val" | sed -e 's/^"//' -e 's/"$//' )
        if [ "$_val" = "null" ]; then
            _val="$_default"
        fi
    fi
    echo "$_val"
}

#  Remove key-value from 'ws/config.json'.
#  This function has two different forms:
#    1. 'jq' query: remove '.jq'
#    2. Field name: remove 'name'
#
#  -param $1 Name of the entry
remove() {
    local _name=${1:-''}
    if [[ "$_name" = \.* ]]; then
        local _val=""
        _val=$( jq "try $_name catch null" "ws/config.json" )
        if [ "$_val" != "null" ]; then
            update "ws/config.json" "del($_name)"
            info "Removed [$_name] from workspace config"
        fi
    else
        local _found=""
        _found=$( jq "has(\"$_name\")" "ws/config.json" )
        if [ "$_found" = "true" ]; then
            update "ws/config.json" "del(.$_name)"
            info "Removed [$_name] from workspace config"
        fi
    fi
}


# ---------- Variables initialization

#  Request protocol:
#+ '<protocol>://any.host/any/endpoint'
_shttp_protocol=""

#  Request domain:
#+ 'https://<domain>/any/endpoint'
_shttp_domain=""

#  Request method.
#  Allowed values:
#+   [GET, POST, PUT, PATCH,
#+   DELETE, HEAD, OPTIONS]
METHOD=""

#  Request endpoint:
#+ 'https://any.host/<endpoint>'
ENDPOINT=""

#  Request headers. Default values
#+ for [Content-Type, Authorization, Host]
#+ could be assigned during request
#+ execution.
HEADERS=()

#  Request body.
BODY=""

#  Request body in parts. During
#+ request execution these parts
#+ will be concatenated.
BODY_PARTS=()

#  Request key-value entries for
#+ data form. If it is specified
#+ default 'Content-Type' header
#+ will be 'multipart/form-data'
#+ otherwise will be 'application/json'.
FORM=()

#  Request key-value entries for
#+ Query Parameters.
QUERY_PARAM=()

#  Additional 'cURL' options.
CURL_OPT=()

#  Authentication mode. Allowed values:
#+ [HEADER, QPARAM, SKIP]
AUTH_MODE=""

#  If value is defined, that command
#+ will be executed as last tasks
#+ of the request.
EDITOR_COMMAND=""


# ---------- Builder functions

#  Setter for '_shttp_protocol'.
#
#  -param $1 Protocol
protocol() {
    local _protocol=${1:-''}
    _shttp_protocol="$_protocol"
    info "Set [Protocol] with [$_shttp_protocol]"
}

#  Setter for '_shttp_domain'.
#
#  -param $1 Domain
domain() {
    local _domain=${1:-''}
    _shttp_domain="$_domain"
    info "Set [Domain] with [$_shttp_domain]"
}


# ---------- Internal functions

#  Key-words used internally like
#+ function names or field names.
#  The functions could be defined
#+ into the main API script if
#+ they are required during request
#+ lifecycle.
readonly _shttp_keywords=(
    'before_api' # Lifecycle function
    'after_api'  # Lifecycle function
)

#  Check if word passed as parameter
#+ exists in the key-words list.
#
#  -param $1 Name of key-word
#  -return '1' if keyword exist
#+         otherwise '0'
_is_keyword() {
    local _name=${1:-''}
    local _found=0
    for _key in "${_shttp_keywords[@]}"; do
        if [ "$_key" = "$_name" ]; then
            _found=1
            break
        fi
    done
    case "$_name" in
        before_* | after_*)
            _found=1
        ;;
    esac
    echo "$_found"
}

#  Check if function is already
#+ declared.
#
#  -param $1 Function name
_has_func() {
    local _func=${1:-''}
    local _exists=1
    #  shellcheck disable=SC2034
    _exists=$( declare -f "$_func" > /dev/null ; echo $? )
    if (( _exists == 0 )); then
        echo 1
    else
        echo 0
    fi
}

#  Execute function if it is
#+ already decared.
#
#  -param $1 Function name
_execute_if_exist() {
    local _func=${1:-''}
    local _has_func=0
    _has_func=$( _has_func "$_func" )
    if (( _has_func == 1 )); then
        $_func
    fi
}

#  Execute request lifecycle:
#    1. Initialize request variables.
#    2. Execute 'before_api' function
#+      if it is declared.
#    3. Execute the command.
#    4. Set request method based on
#+      command name if it was not
#+      assigned during the command
#+      execution.
#    5. Execute the request.
#    6. Execute 'after_api' function
#+      if it is declared.
#    7. Execute open editor task.
#
#  -param $1 Request command
_execute() {
    local _command=${1:-''}
    info "Init request [$_command]"
    _init_vars
    _execute_if_exist before_api
    $_command
    _set_method "$_command"
    _request "$_command"
    _execute_if_exist after_api
    _editor_command
    info "Request [$_command] completed"
}

#  Initilize request variables.
_init_vars() {
    _shttp_protocol="https"
    _shttp_domain=$( get host "" )
    METHOD=""
    ENDPOINT=""
    HEADERS=()
    BODY=""
    BODY_PARTS=()
    FORM=()
    QUERY_PARAM=()
    CURL_OPT=()
    AUTH_MODE="SKIP"
    EDITOR_COMMAND=""
}

#  This lifecycle function is called
#+ for request execution:
#    1. Set the 'URL' value (no protocol).
#    2. Set the 'OUTPUT' basename with
#+      format: 'output/<main-script>.
#+      yyyy-mm-dd.hh_mm_ss'.
#    3. Append default 'Content-Type' to
#+      headers.
#    4. Append authentication to request.
#    5. Set body to a body file.
#    6. Build 'cURL' command.
#    7. Execute 'before_<command>' function
#+      if it is declared.
#    8. Execute 'cURL' command.
#    9. Execute 'after_<command>' function
#+      if it is declared.
#    10. Clean and append details into
#+       'OUTPUT.trace' file.
#
#  -param $1 Request command
_request() {
    local _command=${1:-''}
    eval "URL=\"$URL\""

    OUTPUT="output/$( basename "$0" ).$( date '+%Y-%m-%d.%H_%M_%S' )"

    info "Set METHOD with [$METHOD]"
    info "Set ENDPOINT [$ENDPOINT] to URL"
    info "Set URL with [$URL]"
    info "Set OUTPUT with [$OUTPUT]"

    _append_content_type
    _append_auth

    local _body_file=""
    local _curl=""
    _body_file=$( _append_body_to_file )
    _curl=$( _build_curl "$_body_file" )

    _execute_if_exist "before_${_command}"
    eval "$_curl"
    _execute_if_exist "after_${_command}"

    _clean_trace "$_curl" "$_body_file"

    printf '\n' ; cat "$OUTPUT.trace"
    printf '\n>>>>> response\n' ; cat "$OUTPUT.output"
    printf '\n\n'

    info "Created $OUTPUT.trace"
    info "Created $OUTPUT.output"
}

#  This lifecycle function is called
#+ for request execution:
#    1. Look for request method at
#+      beginning of the command name.
#+      The search is case insensitive.
#+      A valid command must have the
#+      form '<verb><complement-name>',
#+      with one of these verbs: 'get',
#+      'post', 'put', 'patch', 'delete',
#+      'head' or 'options'.
#    2. If command is valid, 'METHOD'
#+      will have the respective verb.
#
#  -param $1 Command name
_set_method() {
    if [ -z "$METHOD" ]; then
        local _command=${1:-''}
        shopt -s nocasematch
        case "$_command" in
            get*)
                METHOD="GET"
            ;;
            post*)
                METHOD="POST"
            ;;
            put*)
                METHOD="PUT"
            ;;
            patch*)
                METHOD="PATCH"
            ;;
            delete*)
                METHOD="DELETE"
            ;;
            head*)
                METHOD="HEAD"
            ;;
            options*)
                METHOD="OPTIONS"
            ;;
        esac
        shopt -u nocasematch
    fi
}

#  Look for existing header by name,
#+ if header does not exist a new
#+ entry is added to 'HEADERS'
#+ otherwise skip assignment.
#
#  -param $1 Header name
#  -param $2 Header value
_append_if_missing_header() {
    local _name=${1:-''}
    local _val=${2:-''}
    shopt -s nocasematch
    local _found=0
    local _length=${#HEADERS[@]}
    if (( _length > 0 )); then
        for _header in "${HEADERS[@]}"; do
            if [[ "$_header" == "$_name:"* ]]; then
                _found=1
                break
            fi
        done
    fi
    shopt -u nocasematch
    if [ $_found = 0 ]; then
        HEADERS+=( "$_name: $_val" )
    fi
}

#  Set value to 'Content-Type' header.
#  If 'FORM' has at least one value
#+ 'Content-Type' will be
#+ 'multipart/form' otherwise will be
#+ 'application/json'.
_append_content_type() {
    local _length=${#FORM[@]}
    if (( _length > 0 )); then
        local _val="multipart/form-data"
    else
        local _val="application/json"
    fi
    _append_if_missing_header "Content-Type" "$_val"
}

#  Setup the authorization mode based
#+ on 'AUTH_MODE':
#    1. HEADER: Set 'Authorization'
#+      header to bearer token type,
#+      token is obtained from
#+      'ws/config.json' using
#+      'apiToken' field.
#+      Set 'Host' header, value is
#+      obtained from 'ws/config.json'
#+      using 'host' field.
#    2. QPARAM: Set to 'URL' a
#+      token as query parameter
#+      with name 'token'. The value
#+      is obtained from 'ws/config.json'
#+      using 'apiToken' field.
#+      Set 'Host' header, value is
#+      obtained from 'ws/config.json'
#+      using 'host' field.
#    3. SKIP: Skip authorization setup.
#    4. Another value: Exit script using
#+      'fatal' logging function.
_append_auth() {
    case "$AUTH_MODE" in
        "HEADER")
            _append_if_missing_header "Authorization" "Bearer $( get apiToken )"
            _append_if_missing_header "Host" "$( get host )"
        ;;
        "QPARAM")
            if [[ "$URL" = *\?* ]]; then
                URL="$URL&token=$( get apiToken )"
            else
                URL="$URL?token=$( get apiToken )"
            fi
            _append_if_missing_header "Host" "$( get host )"
        ;;
        "SKIP")
            :
        ;;
        *)
        fatal "Invalid authorization mode [$AUTH_MODE]"
        ;;
    esac
    info "Set AUTH_MODE with [$AUTH_MODE]"
}

#  First, append every 'BODY_PARTS'
#+ into body content. Using 'BODY_PARTS'
#+ a new line can be done using '\n'
#+ as unique characters in the line.
#  Second, append 'BODY' into body
#+ content.
#  At least one variable must be
#+ appended for generate the body
#+ file.
#
#  -return Body temporal file if
#+         it was generated otherwise
#+         return empty
_append_body_to_file() {
    local _body_file=""
    local _length=${#BODY_PARTS[@]}
    local _appended=0
    _body_file="ws/body.$( date '+%s.%N' ).json.tmp"
    if (( _length > 0 )); then
        for _line in "${BODY_PARTS[@]}"; do
            if [ "$_line" = "\n" ]; then
                echo | tee -a "$_body_file" > /dev/null
            else
                echo "$_line" | tee -a "$_body_file" > /dev/null
            fi
        done
        _appended=$(( _appended+1 ))
    fi
    if [ -n "$BODY" ]; then
        echo "$BODY" | tee -a "$_body_file" > /dev/null
        _appended=$(( _appended+1 ))
    fi
    if (( _appended < 1 )); then
        _body_file=""
    fi
    echo "$_body_file"
}

#  Build 'cURL' command. This
#+ uses the following template:
#    'curl -X <_shttp_method> -s -v -o "<_shttp_output>.output" \
#+       -H "<_shttp_header[1..n]>" \
#+       -d "<_shttp_query_param[1..n]>" \
#+       -F "<_shttp_form[1..n]>" \
#+       --data-binary "@<:body_file>" \
#+       <_shttp_curl_opt[1..n]> \
#+       <_shttp_protocol>://<:url> > "<_shttp_output>.trace" 2>&1'
#
#  -param $1 Body temporal file
#  -return cURL command as string
_build_curl() {
    local _body_file=${1:-''}
    local _curl=(
        "curl -X $METHOD -s -v -o \"$OUTPUT.output\" \\"
    )
    local _length=${#HEADERS[@]}
    if (( _length > 0 )); then
        for _header in "${HEADERS[@]}"; do
            _curl+=( "-H \"$_header\" \\" )
        done
    fi
    _length=${#QUERY_PARAM[@]}
    if (( _length > 0 )); then
        for _param in "${QUERY_PARAM[@]}"; do
            _curl+=( "-d \"$_param\" \\" )
        done
    fi
    _length=${#FORM[@]}
    if (( _length > 0 )); then
        for _form in "${FORM[@]}"; do
            _curl+=( "-F \"$_form\" \\" )
        done
    fi
    if [ -n "$_body_file" ]; then
        _curl+=( "--data-binary \"@$_body_file\" \\" )
    fi
    _length=${#CURL_OPT[@]}
    if (( _length > 0 )); then
        for _opt in "${CURL_OPT[@]}"; do
            _curl+=( "$_opt \\" )
        done
    fi
    _curl+=( "$_shttp_protocol://$URL > \"$OUTPUT.trace\" 2>&1" )
    echo "${_curl[*]}"
}

#  Get a request detail file
#+ based on verbose 'cURL' file.
#  The trace file contains:
#+ request headers, response
#+ headers, request body content,
#+ response body content,
#+ 'cURL' command used.
#
#  -param $1 cURL command
#  -param $2 Body temporal file
_clean_trace() {
    #  shellcheck disable=SC2178
    local _curl=${1:-''}
    local _body_file=${2:-''}

    sed -i -e '/^[*{} ]/d' "$OUTPUT.trace" # Remove unnecessary log lines
    sed -i -e "/^> $/a> {{body}}\n" "$OUTPUT.trace" # Append body tag 
    sed -i -e 's/^..//' "$OUTPUT.trace" # Remove first two characters in each line

    if [ -n "$_body_file" ]; then
        echo "" | tee -a "$OUTPUT.trace" > /dev/null
        echo ">>>>> body" | tee -a "$OUTPUT.trace" > /dev/null
        < "$_body_file" tee -a "$OUTPUT.trace" > /dev/null # Append body content
        rm -rf "$_body_file"
    fi

    echo "" | tee -a "$OUTPUT.trace" > /dev/null
    echo ">>>>> curl" | tee -a "$OUTPUT.trace" > /dev/null
    #  shellcheck disable=SC2128
    echo "$_curl" | tee -a "$OUTPUT.trace" > /dev/null # Append CURL command
}

#  Editor command is used
#+ after request processing.
#  The design was thinking
#+ about to open request
#+ results into file
#+ editor and then process
#+ it manually.
#  Execution takes two steps:
#    1. Variables resolution
#+      if any exist in the
#+      original definition.
#    2. Command execution.
_editor_command() {
    if [ -n "$EDITOR_COMMAND" ]; then
        eval "EDITOR_COMMAND=\"$EDITOR_COMMAND\""
        info "Set EDITOR_COMMAND with [$EDITOR_COMMAND]"
        eval "$EDITOR_COMMAND"
    fi
}

#  Cleanup all temp JSON files from
#+ workspace.
#  This function is called after
#+ execute the main code or after
#+ get an error.
_finally_http_api() {
    if [ -d ws ]; then
        rm -rf ws/*.json.tmp
    fi
}


# ---------- Option functions

#  Look for parameters belong
#+ to option. Parameters are
#+ collected and they are sent
#+ to 'callback' function.
#  Search is interrupted
#+ if another option is found
#+ in the parameters.
#  Valid options have the form:
#+ '--<option>'.
#
#  -param $1 Callback function
#  -param $2 Looked option
#  -param $* Input parameters
_look_for_params() {
    local _callback=${1:-''}
    local _option=${2:-''}
    local _params=()
    local _found=0
    shift 2
    for _param in "$@"; do
        if [ $_found = 1 ]; then
            if [[ "$_param" == "--"* ]]; then
                break
            else
                _params+=( "$_param" )
            fi
        fi
        if [ "$_param" = "$_option" ]; then
            _found=1
        fi
    done
    if [ $_found = 1 ]; then
        $_callback "${_params[@]}"
        return 0
    else
        return 1
    fi
}

#  List the names of main script
#+ functions. Names contained
#+ in the 'keywords' are discarded.
_list_commands() {
    declare -a _functions=(
        $( declare -F )
    )
    local _length=${#_functions[@]}
    if (( _length > 0 )); then
        for _function in "${_functions[@]}"; do
            local _name=""
            local _belong=""
            local _is_key=0
            _name=$( echo "$_function" | cut -d ' ' -f 3 )
            _belong=$( grep "${_name}\s*()" "$0" )
            _is_key=$( _is_keyword "$_name" )
            if [ -n "$_belong" ] \
                   && [[ "$_name" != "_"* ]] \
                   && (( _is_key == 0 )); then
                echo "$_name"
            fi
        done
    fi
}
expr "$*" : ".*--list" > /dev/null \
    && _list_commands \
    && exit 0

#  Add a new variable, into script,
#+ which will be taken as priority
#+ config for 'get' function.
#
#  -param $1 Name of the entry
#  -param $2 Value of the entry
_set_config() {
    local _name=${1:-''}
    local _val=${2:-''}
    eval "$_name=$_val"
    info "Set temporal [$_name] with value [$_val]"
}
expr "$*" : ".*--set" > /dev/null \
    && _look_for_params "_set_config" "--set" "$@"

#  Save key-value to 'ws/config.json'
#+ using 'put' function.
#
#  -param $1 Name of the entry
#  -param $2 Value of the entry
_add_config() {
    local _name=${1:-''}
    local _val=${2:-''}
    put "$_name" "$_val"
}
expr "$*" : ".*--add" > /dev/null \
    && _look_for_params "_add_config" "--add" "$@" \
    && exit 0

#  Get key-value from 'ws/config.json'
#+ using 'get' function.
#
#  -param $1 Name of the entry
_get_config() {
    local _name=${1:-''}
    local _val=""
    if [ -n "$_name" ]; then
        _val=$( get "$_name" )
    fi
    echo "$_val"
}
expr "$*" : ".*--get" > /dev/null \
    && _look_for_params "_get_config" "--get" "$@" \
    && exit 0

#  Remove key-value to 'ws/config.json'
#+ using 'remove' function.
#
#  -param $1 Name of the entry
_remove_config() {
    local _name=${1:-''}
    remove "$_name"
}
expr "$*" : ".*--remove" > /dev/null \
    && _look_for_params "_remove_config" "--remove" "$@" \
    && exit 0

#  List the keys of 'ws/config.json'.
_get_config_keys() {
    local _keys=(
        $( jq "keys | .[]" "ws/config.json" )
    )
    local _length=${#_keys[@]}

    if (( _length > 0 )); then
        for _key in "${_keys[@]}"; do
            echo "$_key" | sed -e 's/^"//' -e 's/"$//'
        done
    fi
}
expr "$*" : ".*--get-keys" > /dev/null \
    && _get_config_keys \
    && exit 0

#  Set host value to 'ws/config.json'.
#  Execution takes the following steps:
#    1. Get host from the parameter.
#    2. Get current host from
#+      'ws/config.json', if parameter
#+      is empty.
#    3. Look for a host from listed
#+      array 'hosts' defined in
#+      'ws/config.json'. Array
#+      must have the form:
#+      '[{key:"" , value:""}]''
#    4. If exist host in listed
#+      hosts, that will be the
#+      current host.
#
#  -param $1 Name of the host or
#+           host value
_set_host() {
    local _host=${1:-''}
    if [ -z "$_host" ]; then
        _host=$( get host )
    fi
    local _val=""
    _val=$( get "hosts | .[] | select(.key==\"$_host\") | .value" )
    if [ -n "$_val" ] && [ "$_val" != "null" ]; then
        _host="$_val"
    fi
    domain "$_host"
    put host "\"$_host\""
}
expr "$*" : ".*--host" > /dev/null \
    && _look_for_params "_set_host" "--host" "$@"

#  Set '_shttp_domain' to 'localhost'. Default
#+ port is 8080 but it can be specified
#+ as first parameter and will override
#+ default port.
#  Protocol is changed as well and takes
#+ 'http' as value.
#
#  -param $1 Port value
_set_localhost() {
    local _port=${1:-''}
    if [ -z "$_port" ]; then
        _port="8080"
    fi
    protocol "http"
    domain "localhost:$_port"
}
expr "$*" : ".*--local" > /dev/null \
    && _look_for_params "_set_localhost" "--local" "$@"

#  Set 'AUTH_MODE' to 'HEADER'.
_auth_header() {
    AUTH_MODE="HEADER"
}
expr "$*" : ".*--auth-header" > /dev/null \
    && _auth_header "$@"

#  Set 'AUTH_MODE' to 'QPARAM'.
_auth_qparam() {
    AUTH_MODE="QPARAM"
}
expr "$*" : ".*--auth-qparam" > /dev/null \
    && _auth_qparam "$@"

#  Get saved editor command from
#+ 'ws/config.json and the value
#+ is assigned to 'EDITOR_COMMAND'.
_open_editor() {
    EDITOR_COMMAND="$( get editorCommand )"
}
expr "$*" : ".*--open" > /dev/null \
    && _open_editor "$@"

#  Clean all files from 'output'
#+ directory.
_clean_output_files() {
    if [ -d output ]; then
        declare -a _selected=(
            $( find "output" -name "*" -type f )
        )
         local _length=${#_selected[@]}
        if (( _length > 0 )); then
            for _file in "${_selected[@]}"; do
                info "Removed [$_file] output"
            done
            rm -rf output/*
        fi
    fi
}
expr "$*" : ".*--clean" > /dev/null \
    && _clean_output_files \
    && info "Cleaning completed" \
    && exit 0


# ---------- Add-ons

#  Add-on files.
#  Filename must have
#+ the form: '<name>_ext'
declare -a _shttp_add_ons=(
    $( find . -name "*_ext" -type f )
)

#  Add-on files length.
readonly _shttp_add_ons_length=${#_shttp_add_ons[@]}

#  If exists add-on files
#+ they will be sourced.
if (( _shttp_add_ons_length > 0 )); then
    for _add_on in "${_shttp_add_ons[@]}"; do
        eval ". $_add_on"
        info "Add-on [$_add_on] sourced"
    done
else
    info "No add-ons sourced"
fi


# ---------- Main

#  Skip main code flag
readonly _shttp_skip=${SKIP_HTTP_API:-''}

#  Main code:
#    1. Get the 'command' input.
#    2. Set the exist 'main' function flag.
#    3. Discard 'command' if has 'option'
#+      format.
#    4. If 'command' or 'main' is present,
#+      execute request lifecycle: '_execute'.
#    5. Finally function is executed.
if [ "$_shttp_skip" != "true" ]; then
    trap _finally_http_api EXIT

    readonly _shttp_command=${1:-''}
    readonly _has_shttp_main=$( _has_func main )

    if [[ "$_shttp_command" == "--"* ]]; then
        _shttp_command=""
    fi

    if [ -n "$_shttp_command" ]; then
        _execute "$_shttp_command"
    elif (( _has_shttp_main == 1 )); then
        _execute main
    else
        info "No command to execute"
    fi
fi
