#! /usr/bin/env bash
#  Run 'shellcheck' for project.
#  https://github.com/koalaman/shellcheck
#  -author Giovanni Farfan B.
set -euo pipefail
IFS=$'\n\t'

shellcheck shttp
shellcheck lint
shellcheck runtests
shellcheck mkexec
shellcheck incver
shellcheck test/test_*
shellcheck test/unit/*
shellcheck test/mock/*_mock
shellcheck sample/gist_comments
shellcheck sample/github_oauth
shellcheck sample/ext/*
