#! /usr/bin/env bash
#  Run all integration tests of the project.
#  -author Giovanni Farfan B.
#
#  -param $1 Sample username
#  -param $2 Sample password
#  -param $3 Sample key
#  -param $4 Sample secret
#  -param $5 (Optional) Slack webhook path
set -euo pipefail
IFS=$'\n\t'

echo "Running Integration Tests..."

#  Slack option '--slack' if $5 is not empty
#+ otherwise empty
_slack_opt=""

_finally_run_samples() {
    local _code=$?
    exit $_code
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap _finally_run_samples EXIT

    (
        cd sample

        #  Setting credential
        ./github_oauth --cred sample \
            --part -u "$1" \
            --part -p "$2" \
            --part -k "$3" \
            --part -s "$4"

        #  Setting Slack webhook path
        _slack_srv=${5:-}
        if [ -n "$_slack_srv" ]; then
            ./github_oauth --add slackSrv "$_slack_srv" -h
            _slack_opt="--slack"
        fi

        #  GitHub authentication
        ./github_oauth delete_auth "$_slack_opt"
        ./github_oauth put_auth "$_slack_opt"
        ./github_oauth check_auth "$_slack_opt"

        #  Executing samples
        ./gist_comments flow_comment "$_slack_opt"
    )
fi
