#! /usr/bin/env bash
#  Run all integration tests of the project.
#  -author Giovanni Farfan B.
#
#  -param $1 Sample username
#  -param $2 Sample token
#  -param $3 (Optional) Slack webhook path
set -euo pipefail
IFS=$'\n\t'

echo "Running Integration Tests..."

#  Slack option '--slack' if $5 is not empty
#+ otherwise empty
_slack_opt=""

_finally_run_samples() {
    local _code=$?
    exit $_code
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap _finally_run_samples EXIT

    (
        cd sample

        #  Setting credential
        ./gist_comments --cred sample \
            --part -u "$1" \
            --part -p "$2"

        #  Setting Slack webhook path
        _slack_srv=${3:-}
        if [ -n "$_slack_srv" ]; then
            ./gist_comments --add slackSrv "$_slack_srv" -h
            _slack_opt="--slack"
        fi

        #  Executing samples
        ./gist_comments flow_comment "$_slack_opt"
    )
fi
