#! /usr/bin/env bash
#  -author Giovanni Farfán B.

before_api() {
    basePath "/gists/"
    put host "\"api.github.com\""
    put githubApiVersion "\"v3\""
    put gistId "\"64ac4a848e1b483bf63443cf9a2c8f59\""
}

get_all() {
    endpoint "$( get gistId )/comments"
}

get_comment() {
    endpoint "$( get gistId )/comments/$( get commentId )"
}

post_comment() {
    endpoint "$( get gistId )/comments"
    headers \
        "Content-Type: application/vnd.github.$( get githubApiVersion ).full+json" \
        "Accept: application/vnd.github.$( get githubApiVersion ).full+json"
    body '{ "body": "shTTP comment" }'
}

after_post_comment() {
    put commentId '.id'
}

patch_comment() {
    endpoint "$( get gistId )/comments/$( get commentId )"
    body '{ "body": "shTTP comment update" }'
}

delete_comment() {
    endpoint "$( get gistId )/comments/$( get commentId )"
}

after_api() {
    remove gistId
}

. ../http_api
