#! /usr/bin/env bash
#  -author Giovanni Farfán B.

before_api() {
    basePath "/gists/$( get gistId )/comments"
    headers \
        "User-Agent: $( get appName )" \
        "Accept: application/vnd.github.$( get apiVersion ).full+json" \
        "Content-Type: application/vnd.github.$( get apiVersion ).full+json"
}

get_all() {
    :
}

get_comment() {
    endpoint "/$( get commentId )"
}

before_post_comment() {
    :
}

post_comment() {
    credential sample
    authMode HEADER
    body '{ "body": "shTTP-samples comment" }'
}

after_post_comment() {
    isTrue "Id not found" "\"$( getOutput id )\" != \"null\""
    put commentId '.id'
}

patch_comment() {
    endpoint "/$( get commentId )"
    body '{ "body": "shTTP-samples comment update" }'
}

delete_comment() {
    endpoint "/$( get commentId )"
}

after_delete_comment() {
    remove commentId
}

after_api() {
    :
}

# ./gist_comment flow_comment --auth-header sample
flow_comment() {
    step post_comment # Internally has defined credential and auth mode
    step patch_comment --auth-header sample # Explicit credential ans auth mode definition
    step delete_comment # Inherit credential and auth mode
}

#  shellcheck disable=SC1091
. ../http_api
