#! /usr/bin/env bash
#  -author Giovanni Farfán B.

before_api() {
    basePath "/authorizations"
}

#  ./github_oauth get_auths --auth-basic gfb --set otp <2fa-token>
get_auths() {
    headers "X-GitHub-OTP: $( get otp )"
}

before_put_auth() {
    put fingerprint "\"$( _random_str 25 )\""
}

#  ./github_oauth put_auth --auth-basic gfb --set otp <2fa-token>
put_auth() {
    endpoint "/clients/$( get clientId )"
    headers "X-GitHub-OTP: $( get otp )"
    body "{
            \"scopes\": [
                \"gist\"
            ],
            \"note\": \"Execute shTTP samples\",
            \"client_secret\": \"$( get clientSecret )\",
            \"fingerprint\": \"$( get fingerprint )\"
        }"
}

after_put_auth() {
    local _last_token=""
    _last_token=$( getOutput token )
    if [ -n "$_last_token" ]; then
        put 'token' '.token'
    fi
    put 'authId' '.id'
}

#  ./github_oauth check_auth
check_auth() {
    method GET
    basePath "/applications/$( get clientId )/tokens/$( get token )"
    curlOpts "--basic" "-u $( get clientId ):$( get clientSecret )"
}

after_check_auth() {
    isTrue "Empty authorization token" "-n \"$( getOutput token )\""
    put 'token' '.token'
}

#  ./github_oauth delete_auth --auth-basic gfb --set otp <2fa-token>
delete_auth() {
    endpoint "/$( get authId )"
    headers "X-GitHub-OTP: $( get otp )"
}

#  shellcheck disable=SC1091
. ../http_api
