#! /usr/bin/env bash
#  -author Giovanni Farfán B.

before_api() {
    basePath "/authorizations"
}

#  ./github_oauth get_auths --auth-basic sample --set otp <2fa-token>
get_auths() {
    headers "X-GitHub-OTP: $( get otp )"
}

before_put_auth() {
    #  Hidden value
    put fingerprint "\"$( _str 25 )\"" PRIVATE
}

#  ./github_oauth put_auth --auth-basic sample --set otp <2fa-token>
put_auth() {
    endpoint "/clients/$( getPart key )"
    headers "X-GitHub-OTP: $( get otp )"
    body "{
            \"scopes\": [
                \"gist\"
            ],
            \"note\": \"Execute shTTP samples\",
            \"client_secret\": \"$( getPart secret )\",
            \"fingerprint\": \"$( get fingerprint )\"
        }"
}

after_put_auth() {
    local _last_token=""
    _last_token=$( getOutput token )
    if [ -n "$_last_token" ]; then
        putPart 'token' "$_last_token"
    fi
    #  Hidden value
    put 'authId' '.id' PRIVATE
}

#  ./github_oauth check_auth
check_auth() {
    method GET
    credential sample
    basePath "/applications/$( getPart key )/tokens/$( getPart token )"
    curlOpts "--basic" "-u $( getPart key ):$( getPart secret )"
}

after_check_auth() {
    local _token=""
    _token=$( getOutput token )
    putPart 'token' "$_token"
}

#  ./github_oauth delete_auth --auth-basic sample --set otp <2fa-token>
delete_auth() {
    endpoint "/$( get authId )"
    headers "X-GitHub-OTP: $( get otp )"
}

#  shellcheck disable=SC1091
. ../http_api
