#! /usr/bin/env bash
#  Tests for 'http_api' public functions.
#  -author Giovanni Farfán B.


#  -test Is true assertion
_input="true"
isTrue "Is false" "-n \"$_input\""
isTrue "Is false" "-z \"$_input\""
#  shellcheck disable=SC2154
assertEquals "Incorrect number of assertions for 'isTrue'" 2 "$_shttp_assertions"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of failures for 'isTrue'" 1 "$_shttp_failures"

_shttp_assertions=0
_shttp_failures=0


#  -test Is false assertion
_input=""
isFalse "Is true" "-n \"$_input\""
isFalse "Is true" "-z \"$_input\""
#  shellcheck disable=SC2154
assertEquals "Incorrect number of assertions for 'isFalse'" 2 "$_shttp_assertions"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of failures for 'isFalse'" 1 "$_shttp_failures"

_shttp_assertions=0
_shttp_failures=0


#  -test Are equals assertion
_input="5"
areEquals "Are not equals" 5 "$_input"
areEquals "Are not equals" 10 "$_input"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of assertions for 'areEquals'" 2 "$_shttp_assertions"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of failures for 'areEquals'" 1 "$_shttp_failures"

_shttp_assertions=0
_shttp_failures=0


#  -test Are not equals assertion
_input="5"
areNotEquals "Are equals" 10 "$_input"
areNotEquals "Are equals" 5 "$_input"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of assertions for 'areNotEquals'" 2 "$_shttp_assertions"
#  shellcheck disable=SC2154
assertEquals "Incorrect number of failures for 'areNotEquals'" 1 "$_shttp_failures"

_shttp_assertions=0
_shttp_failures=0
