#! /usr/bin/env bash
#  Tests for 'http_api' help functions.
#  -author Giovanni Farfán B.


#  -test Show cURL command

post_curl_command() {
    url "http://127.0.0.1:5555/info"
    body '{"name":"test"}'
}

_shttp_command="post_curl_command"
_curl_command=""

_curl_expected_file="curl -X POST -s -v"
_curl_expected_file+=" -H \"Content-Type: application/json\""
_curl_expected_file+=" --data-binary \"@output/curl.tmp.body\""
_curl_expected_file+=" \"http://127.0.0.1:5555/info\""

_show_curl --curl -f _curl_command

assertEquals "'cURL' command does not match" "$_curl_expected_file" "$_curl_command"

_curl_expected_body="curl -X POST -s -v"
_curl_expected_body+=" -H \"Content-Type: application/json\""
_curl_expected_body+=" --data {name:test}"
_curl_expected_body+=" \"http://127.0.0.1:5555/info\""

_show_curl --curl -c _curl_command

assertEquals "'cURL' command does not match" "$_curl_expected_body" "$_curl_command"

_curl_command=""
#  shellcheck disable=SC2034
_shttp_command=""


#  -test Show help content
_help_content=$( _show_help_content )
assertTrue "Help content is empty" "-n \"$_help_content\""
