#! /usr/bin/env bash
#  Tests for 'shttp' initialization.
#  -author Giovanni Farfan B.


#  -test Output directory exists
assertTrue "Output directory not found" "-d output"


#  -test History directory exists
assertTrue "History directory not found" "-d hist"


#  -test Workspace directory exists
assertTrue "Workspace directory not found" "-d ws"


#  -test Config file exists
assertTrue "Config JSON not found" "-f ws/config.json"


#  -test Credentials file exists
assertTrue "Credentials JSON not found" "-f ws/credentials.json"


#  -test Override file exists
assertTrue "Override JSON not found" "-f ws/.override.json.tmp"
