#! /usr/bin/env bash
#  Tests for 'http_api' option functions.
#  -author Giovanni Farfán B.


#  -test Look for parameters
_shttp_registered_opts["--new"]="_callback_function"
_previous_value=()
_callback_function() {
    #  shellcheck disable=SC2034
    local _opt=${1:-}
    local _new=${2:-}
    _previous_value+=( "$_new" )
}
_look_for_params "--new" "command" \
    "--new" "A" \
    "--save" "key" "\"value\"" \
    "--new" "B" \
    "--new" "C" \
    "--remove" "key" \
    "--new" "D" \
    "--basic"

_found=0
for _val in "${_previous_value[@]}"; do
    case "$_val" in
        A | B | C | D )
            _found=$(( _found+1 ))
        ;;
    esac
done
assertEquals "Invalid parameters length" 4 "$_found"


#  -test Register option
_register_opt --change _change_func
_callback_func="${_shttp_registered_opts[--change]}"
assertEquals "Option not registered" "_change_func" "$_callback_func"


#  -test List available commands
_commands=( $( _list_commands --list ) )
_found=0
for _command in "${_commands[@]}"; do
    case "$_command" in
        info | warning | error | fatal)
            _found=$(( _found+1 ))
        ;;
    esac
done

assertEquals "Command not found" 4 "$_found"


#  -test Copy environment
_copy_env --copy default env
assertTrue "Configuration 'env' file does not exist" "-f ws/config.env.json"
assertTrue "Credentials 'env' file does not exist" "-f ws/credentials.env.json"

rm -f ws/config.env.json
rm -f ws/credentials.env.json


#  -test Remove environment
echo '{ }' > ws/config.temp.json
echo '[ ]' > ws/credentials.temp.json

_del_env --del temp

assertFalse "Configuration 'env' file exists" "-f ws/config.temp.json"
assertFalse "Credentials 'env' file exists" "-f ws/credentials.temp.json"


#  -test Add option
_add_config --add "addedVal" "\"value\""
_added_val=$( get addedVal )
assertEquals "'addedVal' not found" "value" "$_added_val"


#  -test Get option
put expectedVal "\"value\""
_expected_val=$( _get_config --get "expectedVal" )
assertEquals "'expectedVal' not found" "value" "$_expected_val"


#  -test Remove option
put removedVal "\"value\""
_remove_config --remove "removedVal"
_null_val=$( get removedVal )
assertIsNull "'removedVal' found" "$_null_val"


#  -test Add part option
_shttp_auth_credential="add-part-opt"
update "ws/credentials.json" '. + [{
        "id": "add-part-opt"
    }]'

_add_part --part -u test.user
_part_val=$( getPart username )
assertEquals "'username' not found" "test.user" "$_part_val"

_add_part --part -p t35t
_part_val=$( getPart password )
assertEquals "'password' not found" "t35t" "$_part_val"

_add_part --part -k 12345
_part_val=$( getPart key )
assertEquals "'key' not found" "12345" "$_part_val"

_add_part --part -s 1234567890
_part_val=$( getPart secret )
assertEquals "'secret' not found" "1234567890" "$_part_val"

_add_part --part -t 0987654321
_part_val=$( getPart token )
assertEquals "'token' not found" "0987654321" "$_part_val"

_add_part --part tokenParam access_token
_part_val=$( getPart tokenParam )
assertEquals "'tokenParam' not found" "access_token" "$_part_val"

_add_part --part keyParam clientId
_part_val=$( getPart keyParam )
assertEquals "'keyParam' not found" "clientId" "$_part_val"

_add_part --part secretParam clientSecret
_part_val=$( getPart secretParam )
assertEquals "'secretParam' not found" "clientSecret" "$_part_val"

_shttp_auth_credential=""


#  -test Get keys option
put namedKey -1
_keys=( $( _get_config_keys --keys ) )
_found=0
for _key in "${_keys[@]}"; do
    if [ "$_key" = "namedKey" ]; then
        _found=1
        break;
    fi
done

assertEquals "'namedKey' key not found" 1 "$_found"


#  -test Clean option
echo '{}' > output/cleanable_output.json

_clean_output_files --clean

assertFalse "Output file is currently exists" "-f output/cleanable_output.json"


#  -test Set environment
echo '{ }' > ws/config.test.json
echo '[ ]' > ws/credentials.test.json

_set_env --env "test"

#  shellcheck disable=SC2154
assertEquals "Configuration 'test' file not found" "ws/config.test.json" "$_shttp_env"
#  shellcheck disable=SC2154
assertEquals "Credentials 'test' file not found" "ws/credentials.test.json" "$_shttp_creds"

_set_env --env
rm -f ws/config.test.json
rm -f ws/credentials.test.json


#  -test Set credential
_set_credential --cred "test.set"
#  shellcheck disable=SC2154
assertEquals "Set credential does not work" "test.set" "$_shttp_auth_credential"
_shttp_auth_credential=""


#  -test Set option
_set_config --set "priorityVal" "\"value\""
put priorityVal "\"new.value\""
_priority_val=$( get priorityVal )
assertEquals "Unexpected 'setConfig' value" "value" "$_priority_val"


#  -test Local option
_set_localhost --local "5555"
#  shellcheck disable=SC2154
assertEquals "Localhost not assigned" "localhost:5555" "$_shttp_domain"


#  -test Set authentication credential option
_set_auth_mode --auth-basic "test.user"
#  shellcheck disable=SC2154
assertEquals "Credential not assigned" "test.user" "$_shttp_auth_credential"
#  shellcheck disable=SC2154
assertEquals "Authorization mode not assigned" "BASIC" "$_shttp_auth_mode"
_shttp_auth_mode=""


#  -test Set request execution times option
_set_times --times 5
#  shellcheck disable=SC2154
assertEquals "Request execution times not assigned" 5 "$_shttp_request_times"
_shttp_request_times=0


#  -test Open editor option
put editorCommand "\"echo \\\"opening... results.json\\\"\""
_open_editor --open
#  shellcheck disable=SC2154
assertEquals "'_shttp_editor_command' not assigned" \
    "echo \\\"opening... results.json\\\"" "$_shttp_editor_command"
