#! /usr/bin/env bash
#  Tests for 'http_api' public functions.
#  -author Giovanni Farfán B.


#  -test Request step flow
_shttp_output_flow="output/flow"
_step_executed="Not executed yet"
get_repo_step() {
    url "http://127.0.0.1:5555/info"
    _step_executed="Executed-step"
}
step get_repo_step
assertEquals "'step_get_repo' not executed" "Executed-step" "$_step_executed"
#  shellcheck disable=SC2034
_shttp_output_flow=""


#  -beforeTests
output "output/public-output.$( date '+%s.%N' )"
#  shellcheck disable=SC2154
echo '{"id":"5s43u-323we"}' > "$_shttp_output.output"


#  -test Update JSON config file
update "ws/config.json" ". + { \"update\": \"updated\" }"
_update=$( < "ws/config.json" jq ".update" )
assertEquals "'update' not found" "\"updated\"" "$_update"

update "ws/config.json" "del(.update)"
_update=$( < "ws/config.json" jq ".update" )
assertIsNull "'update' found" "$_update"


#  -test Put key-value config
put '.id'
_id=$( < "ws/config.json" jq ".id" )
assertEquals "'id' not found" "\"5s43u-323we\"" "$_id"

put 'jqId' '.id'
_jqId=$( < "ws/config.json" jq ".jqId" )
assertEquals "'jqId' not found" "\"5s43u-323we\"" "$_jqId"

put 'rawId' '"4jj43-34mdwe"'
_rawId=$( < "ws/config.json" jq ".rawId" )
assertEquals "'rawId' not found" "\"4jj43-34mdwe\"" "$_rawId"

put 'idx' 5
_idx=$( < "ws/config.json" jq ".idx" )
assertEquals "'idx' not found" "5" "$_idx"

put 'flag' true
_flag=$( < "ws/config.json" jq ".flag" )
assertEquals "'flag' not found" "true" "$_flag"

put 'null' null
_null=$( < "ws/config.json" jq ".null" )
assertIsNull "'null' not found" "$_null"

put 'object' '{}'
_object=$( < "ws/config.json" jq ".object" )
assertEquals "'object' not found" "{}" "$_object"

put 'hidden' 'non-visible' PRIVATE
_hidden=$( < "ws/config.json" jq ".hidden" )
assertIsNull "'hidden' found" "$_hidden"

#  shellcheck disable=SC2154
_hidden_key="$_shttp_suffix->hidden:="
_hidden_key=$( echo "$_hidden_key" | base64 )
_hidden_val=$( grep -e "^$_hidden_key" "ws/.vlt" )

assertEquals "'hidden' value not found" \
    "ZGVmYXVsdC0+aGlkZGVuOj0K!bm9uLXZpc2libGUK" \
    "$_hidden_val"


#  -test Get key-value config
_id=$( get id )
assertEquals "'id' not found" "5s43u-323we" "$_id"

_jqId=$( get jqId )
assertEquals "'jqId' not found" "5s43u-323we" "$_jqId"

_rawId=$( get rawId )
assertEquals "'rawId' not found" "4jj43-34mdwe" "$_rawId"

_idx=$( get idx )
assertEquals "'idx' not found" "5" "$_idx"

_flag=$( get flag )
assertEquals "'flag' not found" "true" "$_flag"

_null=$( get null )
assertIsNull "'null' not found" "$_null"

_object=$( get object )
assertEquals "'object' not found" "{}" "$_object"

_default_value=$( get unknown "default" )
assertEquals "'default' found" "default" "$_default_value"

_unknown=$( get unknown )
assertIsNull "'unknown' found" "$_unknown"

#  shellcheck disable=SC2034
update "ws/.override.json.tmp" ". + { \"tempConfig\": \"7wjedw9djwejd\" }"
_temp_config=$( get tempConfig )
assertEquals "'tempConfig' not found" "7wjedw9djwejd" "$_temp_config"

echo "ZGVmYXVsdC0+bm9uVmlzaWJsZTo9Cg==!aGlkZGVuCg==" \
    | tee -a "ws/.vlt" > /dev/null

_non_visible=$( get nonVisible )
assertEquals "'nonVisible' part not found" "hidden" "$_non_visible"


#  -test Remove key-value config
remove '.id'
_id=$( get id )
assertIsNull "'id' found" "$_id"

remove jqId
_jqId=$( get jqId )
assertIsNull "'jqId' found" "$_jqId"

remove rawId
_rawId=$( get rawId )
assertIsNull "'rawId' found" "$_rawId"

remove idx
_idx=$( get idx )
assertIsNull "'idx' found" "$_idx"

remove flag
_flag=$( get flag )
assertIsNull "'flag' found" "$_flag"

remove null
_null=$( get null )
assertIsNull "'null' found" "$_null"

remove object
_object=$( get object )
assertIsNull "'object' found" "$_object"

remove unknown
_unknown=$( get unknown )
assertIsNull "'unknown' found" "$_unknown"


#  -test Put credential part
_shttp_auth_credential="put-part-test"
update "ws/credentials.json" '. + [{
        "id": "put-part-test"
    }]'
putPart secret hidden
putPart visible "\"shown\"" PUBLIC

_put_part_idx=$( < "ws/credentials.json" \
    jq "map(.id==\"$_shttp_auth_credential\") | index(true)" )

_hidden_val=$( < "ws/credentials.json" jq ".[$_put_part_idx].secret" )
_visible_val=$( < "ws/credentials.json" jq ".[$_put_part_idx].visible" )

assertTrue "Credential parts not found" "-f ws/.vlt"
assertIsNull "Hidden credential part not found" "$_hidden_val"
assertEquals "Visible credential part not found" "\"shown\"" "$_visible_val"

#  shellcheck disable=SC2154
_hidden_key="$_shttp_suffix->$_shttp_auth_credential->secret:="
_hidden_key=$( echo "$_hidden_key" | base64 )
_hidden_val=$( grep -e "^$_hidden_key" "ws/.vlt" )

assertEquals "Hidden value not found" \
    "ZGVmYXVsdC0+cHV0LXBhcnQtdGVzdC0+c2VjcmV0Oj0K!aGlkZGVuCg==" \
    "$_hidden_val"

_shttp_auth_credential=""


#  -test Get credential part
_shttp_auth_credential="get-part-test"
update "ws/credentials.json" '. + [{
        "id": "get-part-test",
        "username": "test",
        "password": "Hidden value",
        "token": "Hidden value",
        "type": "token",
        "key": "12345",
        "secret": "Hidden value",
        "tokenParam": "access_token",
        "keyParam": "clientId",
        "secretParam": "clientSecret",
    }]'
echo "ZGVmYXVsdC0+Z2V0LXBhcnQtdGVzdC0+cGFzc3dvcmQ6PQo=!dDM1dAo=" \
    | tee -a "ws/.vlt" > /dev/null
echo "ZGVmYXVsdC0+Z2V0LXBhcnQtdGVzdC0+dG9rZW46PQo=!MTIzNDU2Nzg5MAo=" \
    | tee -a "ws/.vlt" > /dev/null
echo "ZGVmYXVsdC0+Z2V0LXBhcnQtdGVzdC0+c2VjcmV0Oj0K!MTIzNDU2Nzg5MAo=" \
    | tee -a "ws/.vlt" > /dev/null

_credential_username=""
_credential_password=""
_credential_token=""
_credential_type=""
_credential_token=""
_credential_secret=""
_credential_token_param=""
_credential_key_param=""
_credential_secret_param=""

_credential_username=$( getPart username )
assertEquals "Username part not found" "test" "$_credential_username"

_credential_password=$( getPart password )
assertEquals "Password part not found" "t35t" "$_credential_password"

_credential_token=$( getPart token )
assertEquals "Token part not found" "1234567890" "$_credential_token"

_credential_type=$( getPart type )
assertEquals "Type part not found" "token" "$_credential_type"

_credential_key=$( getPart key )
assertEquals "Key part not found" "12345" "$_credential_key"

_credential_secret=$( getPart secret )
assertEquals "Secret part not found" "1234567890" "$_credential_secret"

_credential_token_param=$( getPart tokenParam )
assertEquals "Token parameter part not found" "access_token" "$_credential_token_param"

_credential_key_param=$( getPart keyParam )
assertEquals "Key parameter part not found" "clientId" "$_credential_key_param"

_credential_secret_param=$( getPart secretParam )
assertEquals "Secret parameter part not found" "clientSecret" "$_credential_secret_param"

_credential_unknown=$( getPart unknown "apiToken" )
assertEquals "Unknown part found" "apiToken" "$_credential_unknown"

_shttp_auth_credential=""


#  -test Get JSON output
_output_value=$( getOutput id )
assertEquals "Output 'id' not found" "5s43u-323we" "$_output_value"


#  -test Get Header
_response_trace=(
    "GET /applications"
    "Host: any.host.com"
    "User-Agent: curl/7.47.0"
    "Accept: */*"
    "Content-Type: application/json"
    ""
    "HTTP/1.1 200 OK"
    "Server: AnyHost.com"
    "Date: Mon, 04 Jun 2018 20:56:50 GMT"
    "Content-Type: application/json; charset=utf-8"
    "Content-Length: 1592"
    "Status: 200 OK"
    "X-RateLimit-Limit: 5000"
    "X-RateLimit-Remaining: 4999"
    "X-RateLimit-Reset: 1528149410"
    "Cache-Control: public, max-age=60, s-maxage=60"
    "Vary: Accept"
)
output "output/trace.$( date '+%s.%N' ).json.tmp"
for _line in "${_response_trace[@]}"; do
    echo "$_line" | tee -a "$_shttp_output.trace" > /dev/null
done

_header_val=$( getHeader 'Content-Type' )
assertEquals "'Content-Type' not found" "application/json; charset=utf-8" "$_header_val"

_header_val=$( getHeader 'X-RateLimit-Limit' )
assertEquals "'X-RateLimit-Limit' not found" "5000" "$_header_val"

_header_val=$( getHeader 'Cache-Control' )
assertEquals "'Cache-Control' not found" "public, max-age=60, s-maxage=60" "$_header_val"

shttp_output=""


#  -test Get HTTP code
_response_trace=(
    "GET /applications HTTP/1.1"
    "Host: any.host.com"
    "Content-Type: application/json"
    ""
    "HTTP/1.1 200 OK"
    "Server: AnyHost.com"
    "Vary: Accept"
    ""
    "http_code: 200"
)
output "output/trace.$( date '+%s.%N' ).json.tmp"
for _line in "${_response_trace[@]}"; do
    echo "$_line" | tee -a "$_shttp_output.trace" > /dev/null
done

_status_code=$( getStatus )
assertEquals "HTTP status not found" "200" "$_status_code"

#  shellcheck disable=SC2034
shttp_output=""
